pipeline {
agent any

environment {
    REGISTRY = "10.0.2.13:5000"
    IMAGE = "app-iky"
    TAG = "${BUILD_NUMBER}"
    FULL_IMAGE = "${REGISTRY}/${IMAGE}:${TAG}"
    KEY = "/root/server-1.pem"

    VM1 = "10.0.1.11"
    VM2 = "10.0.1.12"
}

stages {

    stage('Build Image') {
        steps {
            sh 'docker build -t $IMAGE:$TAG ./app'
        }
    }

    stage('Tag & Push Image') {
        steps {
            sh '''
            docker tag $IMAGE:$TAG $FULL_IMAGE
            docker tag $IMAGE:$TAG $REGISTRY/$IMAGE:latest
            docker push $FULL_IMAGE
            docker push $REGISTRY/$IMAGE:latest
            '''
        }
    }

    stage('Sync Config') {
        steps {
            script {
                def servers = [
                    [ip: VM1, path: "/home/ubuntu/dckr11", monitoring: true],
                    [ip: VM2, path: "/home/ubuntu/dckr12", monitoring: false]
                ]

                for (srv in servers) {
                    sh """
                    scp -i $KEY -o StrictHostKeyChecking=no docker/docker-compose.yml ubuntu@${srv.ip}:${srv.path}/
                    scp -i $KEY -o StrictHostKeyChecking=no -r nginx ubuntu@${srv.ip}:${srv.path}/
                    """

                    if (srv.monitoring) {
                        sh """
                        scp -i $KEY -o StrictHostKeyChecking=no monitoring/docker-compose.monitor.yml ubuntu@${srv.ip}:${srv.path}/
                        scp -i $KEY -o StrictHostKeyChecking=no -r monitoring ubuntu@${srv.ip}:${srv.path}/
                        """
                    }
                }
            }
        }
    }

    stage('Deploy') {
        steps {
            script {
                def servers = [
                    [ip: VM1, path: "/home/ubuntu/dckr11", monitoring: true],
                    [ip: VM2, path: "/home/ubuntu/dckr12", monitoring: false]
                ]

                for (srv in servers) {

                    if (srv.monitoring) {
                        sh """
                        ssh -i $KEY -o StrictHostKeyChecking=no ubuntu@${srv.ip} "
                        cd ${srv.path} &&
                        docker compose pull || true &&
                        docker compose -f docker-compose.yml -f docker-compose.monitor.yml up -d --remove-orphans
                        "
                        """
                    } else {
                        sh """
                        ssh -i $KEY -o StrictHostKeyChecking=no ubuntu@${srv.ip} "
                        cd ${srv.path} &&
                        docker compose pull || true &&
                        docker compose up -d --remove-orphans
                        "
                        """
                    }

                }
            }
        }
    }

}


}